In [1]:
import numpy as np

array = np.random.randint(low=1, high=100, size=(3,3))
print(array)
sum = np.sum(array)
print("\nsum = ", sum)
print("\nmin = ", np.min(array), " index = ", np.argmin(array))
print("max = ", np.max(array), " index = ", np.argmax(array))

print("\nsorted array = \n", np.sort(array))

[[44 73 32]
 [10 95 46]
 [21 32 37]]

sum =  390

min =  10  index =  3
max =  95  index =  4

sorted array = 
 [[32 44 73]
 [10 46 95]
 [21 32 37]]
