In [3]:
import numpy as np

# 1. Створіть двовимірний масив 15x15, що складається з чисел від 1 до 225.
arr = np.arange(1, 226)
arr = arr.reshape((15,15))

print(arr)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [5]:
#2. Обчисліть суму по кожному стовпцю та збережіть результати у вигляді одновимірного масиву.

col_sums = arr.sum(axis = 0)

print(col_sums)

[1590 1605 1620 1635 1650 1665 1680 1695 1710 1725 1740 1755 1770 1785
 1800]


In [6]:
#3. Знайдіть стандартне відхилення елементів масиву.
print(arr.std())

64.95126378036586


In [8]:
#4. Виконайте транспонування масиву.
t_arr = np.transpose(arr)
print(t_arr)

[[  1  16  31  46  61  76  91 106 121 136 151 166 181 196 211]
 [  2  17  32  47  62  77  92 107 122 137 152 167 182 197 212]
 [  3  18  33  48  63  78  93 108 123 138 153 168 183 198 213]
 [  4  19  34  49  64  79  94 109 124 139 154 169 184 199 214]
 [  5  20  35  50  65  80  95 110 125 140 155 170 185 200 215]
 [  6  21  36  51  66  81  96 111 126 141 156 171 186 201 216]
 [  7  22  37  52  67  82  97 112 127 142 157 172 187 202 217]
 [  8  23  38  53  68  83  98 113 128 143 158 173 188 203 218]
 [  9  24  39  54  69  84  99 114 129 144 159 174 189 204 219]
 [ 10  25  40  55  70  85 100 115 130 145 160 175 190 205 220]
 [ 11  26  41  56  71  86 101 116 131 146 161 176 191 206 221]
 [ 12  27  42  57  72  87 102 117 132 147 162 177 192 207 222]
 [ 13  28  43  58  73  88 103 118 133 148 163 178 193 208 223]
 [ 14  29  44  59  74  89 104 119 134 149 164 179 194 209 224]
 [ 15  30  45  60  75  90 105 120 135 150 165 180 195 210 225]]
